concate_type: 0         # -> 0: 2動画を合体、1: 4動画を合体
arrangement: 0          # -> 0: 縦方向、1:横方向
input:
  path_1: ""            # 以下絶対パス
  path_2: ""
  path_3: ""
  path_4: ""
output:
  file_name: "concatenate_kitchen"
  path: ""              # 出力先ディレクトリ
  ext: "mp4"
  title_1: "12:00-12:10"
  title_2: "12:10-12:20"
  title_3: "12:20-12:30"
  title_4: "12:30-12:40"
  color:
    - 255               # Blue
    - 0                 # Green
    - 0                 # Red
  coordination:
    - 10                # x座標
    - 30                # y座標
  fontsize: 1.5
  thickness: 2.0