start_time:  16       # unit: second
end_time: 45          # unit: second
# 以下、絶対パス
input_path: "/media/hishida/ボリューム/10_project/015_GW-retail/002_veloce/009_demo/waiting_time/demo_video_12.mp4"
output_dir: "/home/hishida/Desktop/"